# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=200, verbose_name='天気')),
                ('highest_temperatures', models.IntegerField(default=0, verbose_name='最高気温')),
                ('lowest_temperatures', models.IntegerField(default=0, verbose_name='最低気温')),
                ('chance_of_rain', models.IntegerField(default=0, verbose_name='降水確率')),
                ('precipitation', models.IntegerField(default=0, verbose_name='降水確率')),
                ('wind_speed', models.IntegerField(default=0, verbose_name='風速')),
                ('acquisition_date', models.DateTimeField(verbose_name='取得日時')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Area')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Channel')),
            ],
        ),
    ]
