# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='acquisition_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='取得日時'),
        ),
    ]
