# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20170731_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.IntegerField(blank=True, default=0, verbose_name='風速'),
        ),
    ]
