# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_hourlyweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HourlyWeather',
        ),
    ]
