# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_hourlyweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather.Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='precipitation',
            field=models.PositiveIntegerField(default=0, verbose_name='降水量（mm/h）'),
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='wind_speed',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='風速（m/s）'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='chance_of_rain',
            field=models.PositiveIntegerField(default=0, verbose_name='降水確率（％）'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='風速（m/s）'),
        ),
    ]
