# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20170803_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourlyweather',
            old_name='highest_temperatures',
            new_name='temperatures',
        ),
    ]
