# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20170803_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='weather_type',
            field=models.PositiveIntegerField(choices=[(0, '週間天気'), (1, '今日の天気')], default=0, verbose_name='お天気区分'),
        ),
    ]
