# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_auto_20170805_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyweather',
            name='chance_of_rain',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='降水確率（％）'),
        ),
        migrations.AddField(
            model_name='hourlyweather',
            name='humidity',
            field=models.IntegerField(default=50, verbose_name='湿度（％）'),
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='precipitation',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='降水量（mm/h）'),
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='wind_direction',
            field=models.CharField(max_length=200, verbose_name='風向'),
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='wind_speed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='風速（m/s）'),
        ),
    ]
