# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_auto_20170809_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='area',
        ),
    ]
