# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_remove_weather_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyweather',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather.Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='humidity',
            field=models.PositiveIntegerField(default=50, verbose_name='湿度（％）'),
        ),
    ]
