# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_auto_20170810_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyweather',
            name='temperatures',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4, verbose_name='気温（℃）'),
        ),
    ]
