# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_auto_20170817_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyweather',
            name='chance_of_rain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='降水確率（％）'),
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='precipitation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='降水量（mm/h）'),
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='wind_speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='風速（m/s）'),
        ),
    ]
