# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20170802_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyweather',
            name='time',
            field=models.TimeField(default='00:00:00', verbose_name='時'),
        ),
    ]
