# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_hourlyweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyweather',
            name='date',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='weather.Weather'),
            preserve_default=False,
        ),
    ]
