# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20170802_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyweather',
            name='hourly_weather',
        ),
        migrations.AddField(
            model_name='hourlyweather',
            name='date',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='weather.Weather'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='weather',
            field=models.CharField(default='-', max_length=200, verbose_name='天気'),
        ),
    ]
